#  Extraction de CVs avec Docling
Ce notebook couvre :
- Installation & imports
- Configuration du dossier de CVs
- Extraction batch sur tous les CVs
- Tous les formats d'export (Markdown, JSON, texte brut, HTML)
- Extraction avancée : email, téléphone, liens, structures répétitives

---
##  Cellule 1 — Installation & Imports

In [1]:
# Installation
# À exécuter une seule fois
%pip install -q docling pandas openpyxl

# Imports
from docling.document_converter import DocumentConverter
from pathlib import Path
import json
import re
import pandas as pd
from IPython.display import display, Markdown, HTML

print(" Tout est installé et importé.")

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 162.6/162.6 kB 15.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 68.4/68.4 kB 7.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 519.4/519.4 kB 24.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 280.7/280.7 kB 30.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 94.0/94.0 kB 11.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.2/10.2 MB 95.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.7/42.7 kB 3.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.7/62.7 kB 7.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.7/3.7 MB 43.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 253.0/253.0 kB 21.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 472.8/472.8 kB 46.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.1/15.1 MB 62.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.7/56.7 kB 5.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 68.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.2/79.2 kB 7.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 978.2/978.2 kB 51.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.6/10.6 MB 36.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 635.4/635.4 kB 46.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 94.3/94.3 kB 11.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.7/99.7 kB 11.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 108.1/108.1 kB 12.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 345.0/345.0 kB 18.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 175.3/175.3 kB 19.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 272.8/272.8 kB 16.7 MB/s eta 0:00:00
  Building wheel for pylatexenc (setup.py) ... done
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
typer-slim 0.24.0 requires typer>=0.24.0, but you have typer 0.21.2 which is incompatible.
 Tout est installé et importé.

---
##  Cellule 2 — Configuration

In [2]:
# Dossiers
DOSSIER_CVS   = Path("cv_exemple")      # PDF/DOCX
DOSSIER_OUT   = Path("cv_output")       # dossier de sortie auto-créé

DOSSIER_CVS.mkdir(exist_ok=True)
DOSSIER_OUT.mkdir(exist_ok=True)

# Convertisseur Docling
converter = DocumentConverter()

# Formats acceptés
EXTENSIONS = [".pdf", ".doc", ".docx"]

# Vérification : liste les CVs trouvés
cvs = [f for f in DOSSIER_CVS.iterdir() if f.suffix.lower() in EXTENSIONS]
print(f" Dossier   : {DOSSIER_CVS.resolve()}")
print(f" CVs trouvés : {len(cvs)}")
for cv in cvs:
    print(f"   └─ {cv.name}")

 Dossier   : /content/cv_exemple
 CVs trouvés : 10
   └─ document-mohand-lounici-developpeur-business-intelligence-talend-fdd9cc44.pdf
   └─ document-rachid-laanaya-developpeur-javascript-typescript-react-next-js-angular-node-ef29bc8e (1).pdf
   └─ document-houssemeddine-jebri-senior-developpeur-talend-expert-data-2dfae6a7.pdf
   └─ document-oumaima-kaddaf-consultant-talend-2c92fb94.pdf
   └─ document-sarra-benosman-data-analyst-3434fad6.pdf
   └─ document-hosni-mhemdi-lead-full-stack-javascript-react-angular-nodejs-9-ans-devops-ci-cd-125a16d7.pdf
   └─ document-achref-amari-data-engineer-talend-9-ans-dexperience-7b0cba2e.pdf
   └─ document-sinane-si-mohammed-developpeur-react-js-node-js-dbff0f99 (2).pdf
   └─ document-ayoub-hadi-data-engineer-talend-power-bi-f48843cc.pdf
   └─ document-charaf-kermiche-developpeur-etl-esb-88ef685f.pdf

---
##  Cellule 3 — Extraction batch sur tous les CVs

In [3]:
# Dictionnaire principal : { nom_fichier: result_docling }
resultats = {}
erreurs   = []

for cv_path in cvs:
    try:
        result = converter.convert(cv_path)
        resultats[cv_path.name] = result
        print(f" {cv_path.name}")
    except Exception as e:
        erreurs.append(cv_path.name)
        print(f" {cv_path.name} — Erreur : {e}")

print(f"\n {len(resultats)} CV(s) extraits avec succès, {len(erreurs)} erreur(s).")

[INFO] 2026-05-19 13:13:44,999 [RapidOCR] base.py:22: Using engine_name: torch
[INFO] 2026-05-19 13:13:45,004 [RapidOCR] device_config.py:64: Using GPU device with ID: 0
[INFO] 2026-05-19 13:13:45,008 [RapidOCR] download_file.py:68: Initiating download: https://www.modelscope.cn/models/RapidAI/RapidOCR/resolve/v3.8.0/torch/PP-OCRv4/det/ch_PP-OCRv4_det_mobile.pth
[INFO] 2026-05-19 13:13:46,061 [RapidOCR] download_file.py:82: Download size: 13.83MB
[INFO] 2026-05-19 13:13:46,191 [RapidOCR] download_file.py:95: Successfully saved to: /usr/local/lib/python3.12/dist-packages/rapidocr/models/ch_PP-OCRv4_det_mobile.pth
[INFO] 2026-05-19 13:13:46,194 [RapidOCR] main.py:50: Using /usr/local/lib/python3.12/dist-packages/rapidocr/models/ch_PP-OCRv4_det_mobile.pth
[INFO] 2026-05-19 13:13:47,201 [RapidOCR] base.py:22: Using engine_name: torch
[INFO] 2026-05-19 13:13:47,203 [RapidOCR] device_config.py:64: Using GPU device with ID: 0
[INFO] 2026-05-19 13:13:47,205 [RapidOCR] download_file.py:68: Initiating download: https://www.modelscope.cn/models/RapidAI/RapidOCR/resolve/v3.8.0/torch/PP-OCRv4/cls/ch_ptocr_mobile_v2.0_cls_mobile.pth
[INFO] 2026-05-19 13:13:48,085 [RapidOCR] download_file.py:82: Download size: 0.56MB
[INFO] 2026-05-19 13:13:48,106 [RapidOCR] download_file.py:95: Successfully saved to: /usr/local/lib/python3.12/dist-packages/rapidocr/models/ch_ptocr_mobile_v2.0_cls_mobile.pth
[INFO] 2026-05-19 13:13:48,108 [RapidOCR] main.py:50: Using /usr/local/lib/python3.12/dist-packages/rapidocr/models/ch_ptocr_mobile_v2.0_cls_mobile.pth
[INFO] 2026-05-19 13:13:48,396 [RapidOCR] base.py:22: Using engine_name: torch
[INFO] 2026-05-19 13:13:48,398 [RapidOCR] device_config.py:64: Using GPU device with ID: 0
[INFO] 2026-05-19 13:13:48,400 [RapidOCR] download_file.py:68: Initiating download: https://www.modelscope.cn/models/RapidAI/RapidOCR/resolve/v3.8.0/torch/PP-OCRv4/rec/ch_PP-OCRv4_rec_mobile.pth
[INFO] 2026-05-19 13:13:49,217 [RapidOCR] download_file.py:82: Download size: 25.67MB
[INFO] 2026-05-19 13:13:49,884 [RapidOCR] download_file.py:95: Successfully saved to: /usr/local/lib/python3.12/dist-packages/rapidocr/models/ch_PP-OCRv4_rec_mobile.pth
[INFO] 2026-05-19 13:13:49,887 [RapidOCR] main.py:50: Using /usr/local/lib/python3.12/dist-packages/rapidocr/models/ch_PP-OCRv4_rec_mobile.pth
/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:93: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/770 [00:00<?, ?it/s]

 document-mohand-lounici-developpeur-business-intelligence-talend-fdd9cc44.pdf
 document-rachid-laanaya-developpeur-javascript-typescript-react-next-js-angular-node-ef29bc8e (1).pdf

[WARNING] 2026-05-19 13:14:09,196 [RapidOCR] main.py:132: The text detection result is empty
WARNING:docling.models.stages.ocr.rapid_ocr_model:RapidOCR returned empty result!

 document-houssemeddine-jebri-senior-developpeur-talend-expert-data-2dfae6a7.pdf
 document-oumaima-kaddaf-consultant-talend-2c92fb94.pdf
 document-sarra-benosman-data-analyst-3434fad6.pdf
 document-hosni-mhemdi-lead-full-stack-javascript-react-angular-nodejs-9-ans-devops-ci-cd-125a16d7.pdf
 document-achref-amari-data-engineer-talend-9-ans-dexperience-7b0cba2e.pdf
 document-sinane-si-mohammed-developpeur-react-js-node-js-dbff0f99 (2).pdf

WARNING:docling.models.stages.ocr.rapid_ocr_model:RapidOCR returned empty result!

 document-ayoub-hadi-data-engineer-talend-power-bi-f48843cc.pdf

[WARNING] 2026-05-19 13:14:28,928 [RapidOCR] main.py:132: The text detection result is empty
WARNING:docling.models.stages.ocr.rapid_ocr_model:RapidOCR returned empty result!

 document-charaf-kermiche-developpeur-etl-esb-88ef685f.pdf

 10 CV(s) extraits avec succès, 0 erreur(s).

---
##  Cellule 4 — Export Markdown

In [4]:
#  Affichage du premier CV en Markdown
if resultats:
    premier = list(resultats.keys())[0]
    md_text = resultats[premier].document.export_to_markdown()

    print(f"── Markdown brut : {premier} ──")
    print(md_text[:1500], "...")

    # Rendu visuel dans le notebook
    display(Markdown("---\n**Rendu Markdown :**\n\n" + md_text[:1500]))

# Sauvegarde Markdown de tous les CVs
md_dir = DOSSIER_OUT / "markdown"
md_dir.mkdir(exist_ok=True)

for nom, result in resultats.items():
    out = md_dir / (Path(nom).stem + ".md")
    out.write_text(result.document.export_to_markdown(), encoding="utf-8")

print(f"\n Fichiers .md sauvegardés dans : {md_dir}")

── Markdown brut : document-mohand-lounici-developpeur-business-intelligence-talend-fdd9cc44.pdf ──
## LOUNICI

## Consultant Business Intelligence / Talend / WebService

lounici.mohand@outlook.fr 07 58 39 38 26

Deuil la barre, France

www.linkedin.com/in/mohand-lounici

## EXPÉRIENCE PROFESSIONELLE

BNP PARIBAS -Consultant Business Inteligence / TALEND DI

<!-- image -->

- Juil 2023 -à ce jour

<!-- image -->

## ➢ Entreprise :

BNP Paribas Partner for Innovation est une co-entreprise entre BNP Paribas et IBM, spécialisée dans la gestion des infrastructures informatiques et la transformation numérique pour le secteur bancaire. BP2I offre des services de pointe en matière de cloud, cybersécurité, et gestion de données pour soutenir la performance et l'innovation des institutions financières. Grâce à cette collaboration, BP2I favorise l'agilité et la résilience technologique des opérations bancaires dans un environnement en constante évolution.

<!-- image -->

## ➢ Mission 1 : Amélioration Continue de Juil 2023 à Déc 2023

- Standardisation des contexte s et optimisation des jobs d'alimentations du DataWerhouse existant
- Mettre en place le coffre-fort Vault afin de remplacer les fichiers de configuration et d'assurer la sécurité
- Mettre en place la méthode de gestion des branches GitLab Vs Talend afin de faciliter le travail entre les développeurs puis accompagnements de ces derniers
- Collaborer avec le MOA afin de finaliser les spécifications techniques

<!-- image -->

## ➢ Mission 2 : Projet IRMA de Jan 2024 à ce jour :

Irma a pour objectif d'intégrer des offres co ...

---
**Rendu Markdown :**

## LOUNICI

## Consultant Business Intelligence / Talend / WebService

lounici.mohand@outlook.fr 07 58 39 38 26

Deuil la barre, France

www.linkedin.com/in/mohand-lounici

## EXPÉRIENCE PROFESSIONELLE

BNP PARIBAS -Consultant Business Inteligence / TALEND DI

<!-- image -->

- Juil 2023 -à ce jour

<!-- image -->

## ➢ Entreprise :

BNP Paribas Partner for Innovation est une co-entreprise entre BNP Paribas et IBM, spécialisée dans la gestion des infrastructures informatiques et la transformation numérique pour le secteur bancaire. BP2I offre des services de pointe en matière de cloud, cybersécurité, et gestion de données pour soutenir la performance et l'innovation des institutions financières. Grâce à cette collaboration, BP2I favorise l'agilité et la résilience technologique des opérations bancaires dans un environnement en constante évolution.

<!-- image -->

## ➢ Mission 1 : Amélioration Continue de Juil 2023 à Déc 2023

- Standardisation des contexte s et optimisation des jobs d'alimentations du DataWerhouse existant
- Mettre en place le coffre-fort Vault afin de remplacer les fichiers de configuration et d'assurer la sécurité
- Mettre en place la méthode de gestion des branches GitLab Vs Talend afin de faciliter le travail entre les développeurs puis accompagnements de ces derniers
- Collaborer avec le MOA afin de finaliser les spécifications techniques

<!-- image -->

## ➢ Mission 2 : Projet IRMA de Jan 2024 à ce jour :

Irma a pour objectif d'intégrer des offres co

 Fichiers .md sauvegardés dans : cv_output/markdown

---
##  Cellule 5 — Export Texte brut (.txt)

In [5]:
# Affichage du premier CV en texte brut
if resultats:
    premier = list(resultats.keys())[0]
    txt = resultats[premier].document.export_to_text()
    print(f"── Texte brut : {premier} ──")
    print(txt[:1500], "...")

# Sauvegarde .txt de tous les CVs
txt_dir = DOSSIER_OUT / "txt"
txt_dir.mkdir(exist_ok=True)

for nom, result in resultats.items():
    out = txt_dir / (Path(nom).stem + ".txt")
    out.write_text(result.document.export_to_text(), encoding="utf-8")

print(f"\n Fichiers .txt sauvegardés dans : {txt_dir}")

── Texte brut : document-mohand-lounici-developpeur-business-intelligence-talend-fdd9cc44.pdf ──
LOUNICI

Consultant Business Intelligence / Talend / WebService

lounici.mohand@outlook.fr 07 58 39 38 26

Deuil la barre, France

www.linkedin.com/in/mohand-lounici

EXPÉRIENCE PROFESSIONELLE

BNP PARIBAS -Consultant Business Inteligence / TALEND DI

- Juil 2023 -à ce jour

➢ Entreprise :

BNP Paribas Partner for Innovation est une co-entreprise entre BNP Paribas et IBM, spécialisée dans la gestion des infrastructures informatiques et la transformation numérique pour le secteur bancaire. BP2I offre des services de pointe en matière de cloud, cybersécurité, et gestion de données pour soutenir la performance et l'innovation des institutions financières. Grâce à cette collaboration, BP2I favorise l'agilité et la résilience technologique des opérations bancaires dans un environnement en constante évolution.

➢ Mission 1 : Amélioration Continue de Juil 2023 à Déc 2023

- Standardisation des contexte s et optimisation des jobs d'alimentations du DataWerhouse existant
- Mettre en place le coffre-fort Vault afin de remplacer les fichiers de configuration et d'assurer la sécurité
- Mettre en place la méthode de gestion des branches GitLab Vs Talend afin de faciliter le travail entre les développeurs puis accompagnements de ces derniers
- Collaborer avec le MOA afin de finaliser les spécifications techniques

➢ Mission 2 : Projet IRMA de Jan 2024 à ce jour :

Irma a pour objectif d'intégrer des offres contenant des services IBM / BP2I afin de les exposer pour la partie facturation et  ...

💾 Fichiers .txt sauvegardés dans : cv_output/txt

---
##  Cellule 6 — Export JSON structuré

In [6]:
#  Affichage de la structure JSON du premier CV
if resultats:
    premier = list(resultats.keys())[0]
    data    = resultats[premier].document.export_to_dict()
    print(f"── JSON structuré : {premier} ──")
    print(json.dumps(data, indent=2, ensure_ascii=False)[:2000], "...")

# Sauvegarde JSON de tous les CVs
json_dir = DOSSIER_OUT / "json"
json_dir.mkdir(exist_ok=True)

for nom, result in resultats.items():
    out = json_dir / (Path(nom).stem + ".json")
    with open(out, "w", encoding="utf-8") as f:
        json.dump(result.document.export_to_dict(), f, ensure_ascii=False, indent=2)

print(f"\n Fichiers .json sauvegardés dans : {json_dir}")

── JSON structuré : document-mohand-lounici-developpeur-business-intelligence-talend-fdd9cc44.pdf ──
{
  "schema_name": "DoclingDocument",
  "version": "1.10.0",
  "name": "document-mohand-lounici-developpeur-business-intelligence-talend-fdd9cc44",
  "origin": {
    "mimetype": "application/pdf",
    "binary_hash": 1684323554151307308,
    "filename": "document-mohand-lounici-developpeur-business-intelligence-talend-fdd9cc44.pdf"
  },
  "furniture": {
    "self_ref": "#/furniture",
    "children": [],
    "content_layer": "furniture",
    "name": "_root_",
    "label": "unspecified"
  },
  "body": {
    "self_ref": "#/body",
    "children": [
      {
        "$ref": "#/texts/0"
      },
      {
        "$ref": "#/texts/1"
      },
      {
        "$ref": "#/texts/2"
      },
      {
        "$ref": "#/texts/3"
      },
      {
        "$ref": "#/texts/4"
      },
      {
        "$ref": "#/texts/5"
      },
      {
        "$ref": "#/texts/6"
      },
      {
        "$ref": "#/pictures/0"
      },
      {
        "$ref": "#/groups/0"
      },
      {
        "$ref": "#/pictures/1"
      },
      {
        "$ref": "#/texts/8"
      },
      {
        "$ref": "#/texts/9"
      },
      {
        "$ref": "#/pictures/2"
      },
      {
        "$ref": "#/texts/10"
      },
      {
        "$ref": "#/groups/1"
      },
      {
        "$ref": "#/pictures/3"
      },
      {
        "$ref": "#/texts/15"
      },
      {
        "$ref": "#/texts/16"
      },
      {
        "$ref": "#/groups/2"
      },
      {
        "$ref": "#/pictures/4"
      },
      {
        "$ref": "#/texts/33"
      },
      {
        "$ref": "#/texts/34"
      },
      {
        "$ref": "#/pictures/5"
      },
      {
        "$ref": "#/pictures/6"
      },
      {
        "$ref": "#/pictures/7"
      },
      {
        "$ref": "#/groups/3"
      },
      {
        "$ref": "#/pictures/8"
      },
      {
        "$ref": "#/pictures/9"
      },
      {
        "$ref": "#/pictures/10"
      },
      {
        "$ref": "#/texts/44"
      },
      {
        "$ref": "#/groups/4"
      },
      {
   ...

💾 Fichiers .json sauvegardés dans : cv_output/json

---
##  Cellule 7 — Export HTML

In [7]:
# Affichage HTML du premier CV
if resultats:
    premier  = list(resultats.keys())[0]
    html_str = resultats[premier].document.export_to_html()
    print(f"── HTML : {premier} (aperçu) ──")
    print(html_str[:800], "...")

    # Rendu dans le notebook
    display(HTML(html_str))

# Sauvegarde HTML de tous les CVs
html_dir = DOSSIER_OUT / "html"
html_dir.mkdir(exist_ok=True)

for nom, result in resultats.items():
    out = html_dir / (Path(nom).stem + ".html")
    out.write_text(result.document.export_to_html(), encoding="utf-8")

print(f"\n Fichiers .html sauvegardés dans : {html_dir}")

── HTML : document-mohand-lounici-developpeur-business-intelligence-talend-fdd9cc44.pdf (aperçu) ──
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8"/>
<title>document-mohand-lounici-developpeur-business-intelligence-talend-fdd9cc44</title>
<meta name="generator" content="Docling HTML Serializer"/>
<style>
    html {
        background-color: #f5f5f5;
        font-family: Arial, sans-serif;
        line-height: 1.6;
    }
    body {
        max-width: 800px;
        margin: 0 auto;
        padding: 2rem;
        background-color: white;
        box-shadow: 0 0 10px rgba(0,0,0,0.1);
    }
    h1, h2, h3, h4, h5, h6 {
        color: #333;
        margin-top: 1.5em;
        margin-bottom: 0.5em;
    }
    h1 {
        font-size: 2em;
        border-bottom: 1px solid #eee;
        padding-bottom: 0.3em;
    }
    table {
        border-collapse: collapse;
        margin: 1em 0;
        wid ...

💾 Fichiers .html sauvegardés dans : cv_output/html

---
##  Cellule 8 — Extraction avancée : Email, Téléphone, LinkedIn, GitHub

In [8]:
# Patterns regex pour structures répétitives
PATTERNS = {
    "email":    r'[\w.+\-]+@[\w\-]+\.[\w.]+',
    "telephone": r'(?:\+33|0)[\s.\-]?[1-9](?:[\s.\-]?\d{2}){4}',  # format FR
    "linkedin": r'linkedin\.com/in/[\w\-]+',
    "github":   r'github\.com/[\w\-]+',
    "site_web": r'https?://[\w.\-/]+',
}

def extraire_champs(texte: str) -> dict:
    """Extrait les champs structurés d'un texte brut."""
    return {
        champ: list(set(re.findall(pattern, texte, re.IGNORECASE)))
        for champ, pattern in PATTERNS.items()
    }

# Application sur tous les CVs
champs_extraits = []

for nom, result in resultats.items():
    texte  = result.document.export_to_text()
    champs = extraire_champs(texte)
    champs["fichier"] = nom
    champs_extraits.append(champs)
    print(f"\n📄 {nom}")
    for k, v in champs.items():
        if k != "fichier" and v:
            print(f"   {k:12} → {v}")

df_champs = pd.DataFrame(champs_extraits)
display(df_champs)

📄 document-mohand-lounici-developpeur-business-intelligence-talend-fdd9cc44.pdf
   email        → ['lounici.mohand@outlook.fr']
   telephone    → ['07 58 39 38 26']
   linkedin     → ['linkedin.com/in/mohand-lounici']
   site_web     → ['https://www.fyi-consulting.fr/']

📄 document-rachid-laanaya-developpeur-javascript-typescript-react-next-js-angular-node-ef29bc8e (1).pdf
   email        → ['laanaya.rashid@gmail.com']
   telephone    → ['+33 6 17 12 43 20']

📄 document-houssemeddine-jebri-senior-developpeur-talend-expert-data-2dfae6a7.pdf
   email        → ['jbhoussem@gmail.com']
   telephone    → ['+33 7 82 12 21 17']

📄 document-oumaima-kaddaf-consultant-talend-2c92fb94.pdf
   email        → ['oumaimakaddaf19@gmail.com']
   telephone    → ['06.27.11.29.60']

📄 document-sarra-benosman-data-analyst-3434fad6.pdf
   email        → ['sarrabenosman88@gmail.com']
   linkedin     → ['linkedin.com/in/sarra-ben-osman']
   site_web     → ['https://www.linkedin.com/in/sarra-ben-osman/']

📄 document-hosni-mhemdi-lead-full-stack-javascript-react-angular-nodejs-9-ans-devops-ci-cd-125a16d7.pdf
   email        → ['emhemdihosni@gmail.com']
   telephone    → ['07 81 63 26 53']

📄 document-achref-amari-data-engineer-talend-9-ans-dexperience-7b0cba2e.pdf
   email        → ['Achref.amari01@gmail.com']
   telephone    → ['+33636124256']

📄 document-sinane-si-mohammed-developpeur-react-js-node-js-dbff0f99 (2).pdf
   email        → ['sin.sim@outlook.fr']
   telephone    → ['0769555407']
   linkedin     → ['linkedin.com/in/kikoane', 'linkedin.com/in/sinane-si-']
   github       → ['github.com/ssi-moha']
   site_web     → ['https://github.com/ssi-moha', 'https://www.linkedin.com/in/sinane-si-', 'https://www.linkedin.com/in/kikoane/']

📄 document-ayoub-hadi-data-engineer-talend-power-bi-f48843cc.pdf
   email        → ['hadi-ayoub@hotmail.com']
   telephone    → ['+33 7 75 71 01 76']

📄 document-charaf-kermiche-developpeur-etl-esb-88ef685f.pdf
   email        → ['charaf.kermiche@gmail.com']
   telephone    → ['06 50 88 09 20']

,email,telephone,linkedin,github,site_web,fichier
0,[lounici.mohand@outlook.fr],[07 58 39 38 26],[linkedin.com/in/mohand-lounici],[],[https://www.fyi-consulting.fr/],document-mohand-lounici-developpeur-business-i...
1,[laanaya.rashid@gmail.com],[+33 6 17 12 43 20],[],[],[],document-rachid-laanaya-developpeur-javascript...
2,[jbhoussem@gmail.com],[+33 7 82 12 21 17],[],[],[],document-houssemeddine-jebri-senior-developpeu...
3,[oumaimakaddaf19@gmail.com],[06.27.11.29.60],[],[],[],document-oumaima-kaddaf-consultant-talend-2c92...
4,[sarrabenosman88@gmail.com],[],[linkedin.com/in/sarra-ben-osman],[],[https://www.linkedin.com/in/sarra-ben-osman/],document-sarra-benosman-data-analyst-3434fad6.pdf
5,[emhemdihosni@gmail.com],[07 81 63 26 53],[],[],[],document-hosni-mhemdi-lead-full-stack-javascri...
6,[Achref.amari01@gmail.com],[+33636124256],[],[],[],document-achref-amari-data-engineer-talend-9-a...
7,[sin.sim@outlook.fr],[0769555407],"[linkedin.com/in/kikoane, linkedin.com/in/sina...",[github.com/ssi-moha],"[https://github.com/ssi-moha, https://www.link...",document-sinane-si-mohammed-developpeur-react-...
8,[hadi-ayoub@hotmail.com],[+33 7 75 71 01 76],[],[],[],document-ayoub-hadi-data-engineer-talend-power...
9,[charaf.kermiche@gmail.com],[06 50 88 09 20],[],[],[],document-charaf-kermiche-developpeur-etl-esb-8...

---
##  Cellule 9 — Extraction avancée : Sections répétitives (Expérience, Formation, Compétences)

In [9]:
# Mots-clés de sections courants dans les CVs (FR + EN)
SECTIONS_KEYWORDS = {
    "experience":   ["expérience", "experience", "emploi", "poste", "parcours professionnel"],
    "formation":    ["formation", "éducation", "education", "diplôme", "diplome", "études", "etudes"],
    "competences":  ["compétences", "competences", "skills", "technologies", "outils", "langages"],
    "langues":      ["langues", "languages"],
    "projets":      ["projets", "projects", "réalisations"],
    "certifications": ["certifications", "certificats", "certifications"],
}

def detecter_sections(texte: str) -> dict:
    """Détecte quelles sections sont présentes dans le CV."""
    texte_lower = texte.lower()
    return {
        section: any(kw in texte_lower for kw in kws)
        for section, kws in SECTIONS_KEYWORDS.items()
    }

def extraire_section_brute(texte: str, keywords: list) -> str:
    """Extrait le texte brut d'une section en cherchant ses keywords."""
    lignes  = texte.split("\n")
    capture = False
    buffer  = []

    for ligne in lignes:
        ll = ligne.lower().strip()
        # Début de section
        if any(kw in ll for kw in keywords) and len(ll) < 60:
            capture = True
            buffer  = [ligne]
            continue
        # Fin de section : nouvelle section détectée
        if capture:
            toutes_kws = [kw for kws in SECTIONS_KEYWORDS.values() for kw in kws]
            if any(kw in ll for kw in toutes_kws) and len(ll) < 60 and buffer:
                break
            buffer.append(ligne)

    return "\n".join(buffer).strip()

# Affichage des sections détectées pour chaque CV
recap_sections = []

for nom, result in resultats.items():
    texte   = result.document.export_to_text()
    present = detecter_sections(texte)
    row     = {"fichier": nom}
    row.update({k: "" if v else "—" for k, v in present.items()})
    recap_sections.append(row)
    print(f"\n {nom}")
    for section, found in present.items():
        if found:
            extrait = extraire_section_brute(texte, SECTIONS_KEYWORDS[section])
            print(f"\n  [{section.upper()}]")
            print(extrait[:400] + ("..." if len(extrait) > 400 else ""))

display(pd.DataFrame(recap_sections))

 document-mohand-lounici-developpeur-business-intelligence-talend-fdd9cc44.pdf

  [EXPERIENCE]
EXPÉRIENCE PROFESSIONELLE

BNP PARIBAS -Consultant Business Inteligence / TALEND DI

- Juil 2023 -à ce jour

➢ Entreprise :

BNP Paribas Partner for Innovation est une co-entreprise entre BNP Paribas et IBM, spécialisée dans la gestion des infrastructures informatiques et la transformation numérique pour le secteur bancaire. BP2I offre des services de pointe en matière de cloud, cybersécurité, et ...

  [FORMATION]
PLB Consultant - Formation Power BI

Oct 2024

Levallois-Perret, France

Institut Galilée paris XIII sorbonne paris cité - Diplôme en master 2 Exploration Informatique des Données et Décisionnelle

2015 - 2016

Villetaneuse, France

Institut Galilée paris XIII sorbonne paris cité - Diplôme Master 1 en Informatique Générale

2014 - 2015

Villetaneuse, France

  [COMPETENCES]
COMPÉTENCES

- Cloud : Azure DP900
- Business Intelligence / ETL : Talend Open Studio, TMC, TAC, Microsoft Power BI, IBM Cognos, Qlik Sence
- Base de données : Postgres, oracle database, Oracle SQL,  SQL Server, MySQL.
- Big Data: Hadoop, Spark, Elasticsearch, Kibana.
- Langages : Python, SQL, JavaScript, Java, PHP,  HTML5, CSS
- Gestion de projet : Méthodologies agiles: SCRUM.
- Systèmes d'exploi...

  [LANGUES]
LANGUES

Berbère

Langue maternelle

Arabe

Courant

Français

Courant

Anglais

Technique

CENTRES D'INTÉRÊTS

- Voyage
- Musique
- Sport
- Films et series
- Documenaires

PeopleSpheres -Développeur ETL / WEB SERVICES

Jan 2018 -JUIN 2023

➢ Entreprise :

Peoplespheres est une platforme SaaS qui permet de centraliser et d'interconnecter toutes les données et actions RH, elle per met aux entrepris...

  [PROJETS]


 document-rachid-laanaya-developpeur-javascript-typescript-react-next-js-angular-node-ef29bc8e (1).pdf

  [EXPERIENCE]
EXPÉRIENCE PROFESSIONNELLE

Consultant  Fullstack Senior

Scor

Juin 2024 - Mars 2026

- Piloté le développement frontend de la plateforme saas LEX (analyse et recherche de contrats d'assurance) au sein d'une équipe de 6 développeurs, en livrant des composants React réutilisables (Atomic design) qui ont accéléré l'intégration de nouvelles features.
- Introduire une couche Node.js/Express entre le ...

  [FORMATION]
Diplôme d'Ingénieur en Informatique

EMSI - École Marocaine des Sciences de l'Ingénieur

  [COMPETENCES]


  [LANGUES]
Langues: Français, Anglais

 document-houssemeddine-jebri-senior-developpeur-talend-expert-data-2dfae6a7.pdf

  [EXPERIENCE]
EXPÉRIENCES PROFESSIONNELLES

Senior Développeur - Tech Lead Data

Nov 2024 - En Cours

Nom de l'entreprise Gangeraud Construction | DSI

- Administration de Talend Management Console (TMC) : gestion des environnements (Dev, Recette, Production), des workspaces, des rôles et des droits d'accès.
- Développement et maintenance des flux d'interfaçage entre différentes applications : Cegid, ReadSoft, ...

  [FORMATION]
INFORMATIONS

+33 7 82 12 21 17

jbhoussem@gmail.com

Île-de-France

  [COMPETENCES]
- Compétences avancées en SQL
- Développement Java et Python
- Gestion des flux de données volumineux

CENTRES D'INTÉRÊT

Musique

Voyage

Sport

HOUSSEMEDDINE JEBRI

Tech Lead Data

PROFIL

Ingénieur informatique avec 8 ans d'expérience et une expertise approfondie en Talend. Fort d'une solide expérience professionnelle, je possède une maîtrise avancée des solutions Talend, notamment Talend Data ...

  [LANGUES]
LANGUES

Français : Courant

Anglais : Courant

  [PROJETS]
- Référent Talend sur plusieurs projets.
- Modélisation, Conception, Développement et Alimentation d'un entrepôt de données.
- Externalisation des contextes.
- Développement de routines Java pour implémentation des règles métiers spécifiques.
- Gestion des erreurs et alertes des Jobs, envoie des Emails.
- Création et développement de batchs Talend.
- Tester / Planifier les jobs sur Crontab (Linux)...

  [CERTIFICATIONS]
CERTIFICATIONS

- Microsoft Certified DA-100 : Data Analyst Associate.
- MTA 98-364: Notions Fondamentales des Bases de Données.
- MTA 98-381: Introduction to Programming Using Python.

 document-oumaima-kaddaf-consultant-talend-2c92fb94.pdf

  [EXPERIENCE]
EXPERIENCES PROFESSIONNELLES

Juillet 2022 -Mai 2024

Consultante Talend

Projet BITA : intégration de la bourse italienne

- Rédaction de la documentation de la solution : Création de documents détaillés décrivant l'architecture, les processus et les flux de données pour l'intégration de la Bourse Italienne.
- Développement des jobs Talend : Conception et implémentation de jobs ETL utilisant Tale...

  [FORMATION]
FORMATION

2013 - 2015

Classes préparatoires - Maroc

2015 - 2018

ENSIAS - Ingénieur en e-Management et Business intelligence - Maroc

  [COMPETENCES]
✔ Compétences Fonctionnelles

- Finance
- E-commerce
- RH et Paie

  [LANGUES]
✔ Langues

■

  [PROJETS]


 document-sarra-benosman-data-analyst-3434fad6.pdf

  [FORMATION]
-  Créations d'univers (outil de conception d'information)
-  Développement des rapports à l'aide de BusinessObjects (Web intelligence)
-  Manipulation des données sous ADMINER, PgAdmin

Outils : Talend DI, SAP BO, MySQL, MySQL Workbench, Power BI, Pentaho, pgAdmin

  [COMPETENCES]
COMPETENCES CLES

-  Business Intelligence
-  ETL
-  Talend DI
-  Data warehouse
-  Data modeling
-  Data visualization
-  KPI
-  Data-driven
-  Power BI
-  QlikView
-  Pentaho
-  SAP BO
-  Webi
-  ETL TOOL
-  SQL
-  MySQL Workbench
-  DBeaver
-  MySQL
-  SQL Server
-  Oracle
-  PostgreSQL
-  AS400
-  Microsoft Dynamics NAV
-  R
-  Python
-  Jira
-  Confluence

L  A  N  ...

 document-hosni-mhemdi-lead-full-stack-javascript-react-angular-nodejs-9-ans-devops-ci-cd-125a16d7.pdf

  [EXPERIENCE]
Expériences professionnelles

Karismatik - Senior Full -Stack JavaScript (Depuis septembre 2022) Rôle & responsabilités

  [FORMATION]
Formation

- Cycle d'ingénieur en Télécommunications.
- Licence en Systèmes Informatiques et Logiciels.

  [COMPETENCES]
Systèmes & Outils:

Linux, Windows, VSCode, WebStorm, MongoDB.

  [LANGUES]
Langues

- Français
- Anglais

  [PROJETS]
Réalisations clés

- Mise en place d'une architecture back-end NestJS modulaire
- Création d'un template de projet standardisé adopté par l'équipe
- Accélération du onboarding développeur grâce à Docker + documentation

Proxim IT - Senior Front -End (Août 2019 - Avril 2022) Projet : Bankerise

Solution bancaire digitale (web + mobile) Rôle : Développeur Senior ReactJS

- Développement de modules c...

 document-achref-amari-data-engineer-talend-9-ans-dexperience-7b0cba2e.pdf

  [EXPERIENCE]
EXPERIENCE  PROFESSIONNELLE

CONSULTANT Talend DI/TAC

Client : CEVA LOGISTICS

OCTOBRE 2024 - AUJOURD'HUI

□

□

□

- [ ] Création des spécifications techniques détaillées.

- [ ] Développement de flux ETL pour les données extraites depuis des fichiers, APIs, DBs..

- [ ] Mise en place d'un système de gestion de log pour faire le suivi d'exécution des jobs.

- [ ] □ Migrer les environnement recet...

  [FORMATION]
FORMATION

-  2024 dbt Certified Developer
-  2024 SNOWPRO CORE CERTIFIED
-  2023 Talend API Services Developer Practitioner
-  2023 Talend Cloud Administrator Practitioner
-  2019 Talend Data Integration v7 Certified Developer
-  2017 Diplôme National d'Ingénieur en Informatique (Option : ERP/ Business intelligence)
- ESPRIT : École supérieur privée d'ingénierie et de technologies

  [COMPETENCES]
COMPETENCES

- Compétences Sectorielles                                          Compétences techniques
- Gestion Commerciale
- RH
- Logistique
- Méthodologies
- SCRUM
- Méthodes de conception
- UML

- ETL: Talend Open Studio, Talend Data Integration,TAC, Talend Big Data, Talend ESB, Talend Cloud

- Reporting: Tableau Desktop, Tableau Server, Tableau Online

- Big Data: Hadoop, Hive, OOZIE, Spark
...

 document-sinane-si-mohammed-developpeur-react-js-node-js-dbff0f99 (2).pdf

  [EXPERIENCE]
Développeur React / Node.js +7 ans d'expérience

À PROPOS

0769555407 sin.sim@outlook.fr https://github.com/ssi-moha https://www.linkedin.com/in/sinane-si-

mohammed-10b545164/

Développeur Fullstack passionné et expérimenté. Je maîtrise l'écosystème JavaScript depuis plus de 7 ans, aussi bien côté front (React, React Native) que back (Node.js, GraphQL, MongoDB). J'ai occupé des rôles de contribut...

  [FORMATION]
FORMATION 42 - École de programmation

Paris

2017 - 2018

Faculté des sciences - Licence Informatique Electronique

Dijon

2015 - 2017

RÉFÉRENCES

(Contact sur demande)

Kévin Nguyen - Développeur Fullsack

  [COMPETENCES]
- Langages : JavaScript, T ypeScript •

- Frontend : React.js, React Native, Next.js, Vite.js, Apollo Client •

- Backend : Node.js, Express.js, NestJS, GraphQL, Apollo Server •

- Base de données : MongoDB, PostgreSQL, Redis, SQL •

- Tests : Playwright, Cypress, Jest •

- DevOps : Docker, GitHub Actions, CI/CD, AWS, GCP, Nginx, Ansible •

- Outils : Git, Figma, Postman, Notion, Claude Code, Open...

  [LANGUES]
- Langues : Français (natif), Anglais (professionnel) •

  [PROJETS]


 document-ayoub-hadi-data-engineer-talend-power-bi-f48843cc.pdf

  [EXPERIENCE]
EXPERIENCE PROFESSIONNELLE

Outils : SQL Server, DB2, SSMS , Dbeaver, SQL, Talend Data Integration 7.1 (TIS), Talend Administration Console,Talend Data Integration 8.0, Gitlab, JIRA/Jira cloud

ConsultantDATA &Analytics/ Chef deservice Urbain DATA

ChezCasablancaprestationsde janvier2020a mars2022

Projet : Mise en place de Casa Urban Platform et developpement du portail Open DATA

Client:Commune ...

  [FORMATION]
Diplôme d'Ingénieur en Informatique Décisionnelle

Institut National de Statistique et d'Economie Appliquée (INSEA)

2011-2014

Classes préparatoires aux grandes écoles MPSI/PSI

  [COMPETENCES]
COMPETENCES FONCTIONNELLES

- Rédaction des spécifications fonctionnelles
- Animation des ateliers avec le client +
- Suivi et accompagnement des tests avec l'équipe métier
- Appréhender la faisabilité des exigences fonctionnel

  [LANGUES]


  [CERTIFICATIONS]
CERTIFICATS

- Talend Data Integration Certified Developer (Lien) | Databricks Certified Data Engineer Associate (Lien)

 document-charaf-kermiche-developpeur-etl-esb-88ef685f.pdf

  [EXPERIENCE]
EXPÉRIENCE PROFESSIONNELLE

Lead développeur ETL TALEND

KEOLIS Group | Lyon | Janv. 2025 - présent

- Développement des flux inter-SI réalisant des échanges SFTP.
- Migration des flux ODI et des batch PowerShell vers Talend V8.
- Développement des nouveaux flux inter-applicatifs avec Talend.
- Administration de la Talend Management Console (TMC)

Développeur ETL/ESB

Adecco Group | Lyon | Mai. 20...

  [FORMATION]
FORMATIONS

- Licence Pro en Informatique Décisionnelle, Statistiques et Big Data

Aix-Marseille Université 2018-2019

Master 2 en Gestion des risques

Université de Lorraine 2017-2018

  [COMPETENCES]
- Excellentes compétences relationnelles
- Esprit d'équipe
- Orientation résultats

C H A R A F   K E R M I C H E

DEVELOPPEUR ETL/ESB

Je suis Charaf KERMICHE, 33 ans, développeur ETL/ESB passionné par le data engineering. Mon objectif est d'aider les organisations à développer et optimiser les flux d'intégration de données au sein de leurs systèmes.

,fichier,experience,formation,competences,langues,projets,certifications
0,document-mohand-lounici-developpeur-business-i...,,,,,,—
1,document-rachid-laanaya-developpeur-javascript...,,,,,—,—
2,document-houssemeddine-jebri-senior-developpeu...,,,,,,
3,document-oumaima-kaddaf-consultant-talend-2c92...,,,,,,—
4,document-sarra-benosman-data-analyst-3434fad6.pdf,—,,,—,—,—
5,document-hosni-mhemdi-lead-full-stack-javascri...,,,,,,—
6,document-achref-amari-data-engineer-talend-9-a...,,,,—,—,—
7,document-sinane-si-mohammed-developpeur-react-...,,,,,,—
8,document-ayoub-hadi-data-engineer-talend-power...,,,,,—,
9,document-charaf-kermiche-developpeur-etl-esb-8...,,,,—,—,—

---
## Cellule 10 — Export final consolidé (CSV + Excel)

In [10]:
# Tableau final : champs extraits + sections détectées
df_contact  = pd.DataFrame(champs_extraits)
df_sections = pd.DataFrame(recap_sections)

df_final = df_contact.merge(df_sections, on="fichier", how="outer")

# Ajouter le texte brut complet
df_final["texte_brut"] = df_final["fichier"].apply(
    lambda nom: resultats[nom].document.export_to_text() if nom in resultats else ""
)
df_final["markdown"] = df_final["fichier"].apply(
    lambda nom: resultats[nom].document.export_to_markdown() if nom in resultats else ""
)

# Export CSV
csv_path = DOSSIER_OUT / "cvs_extraits.csv"
df_final.to_csv(csv_path, index=False, encoding="utf-8")
print(f" CSV    → {csv_path}")

# Export Excel
excel_path = DOSSIER_OUT / "cvs_extraits.xlsx"
df_final.drop(columns=["texte_brut", "markdown"]).to_excel(excel_path, index=False)
print(f" Excel  → {excel_path}")

print("\n── Aperçu du tableau final ──")
display(df_final.drop(columns=["texte_brut", "markdown"]))

 CSV    → cv_output/cvs_extraits.csv
 Excel  → cv_output/cvs_extraits.xlsx

── Aperçu du tableau final ──

,email,telephone,linkedin,github,site_web,fichier,experience,formation,competences,langues,projets,certifications
0,[Achref.amari01@gmail.com],[+33636124256],[],[],[],document-achref-amari-data-engineer-talend-9-a...,,,,—,—,—
1,[hadi-ayoub@hotmail.com],[+33 7 75 71 01 76],[],[],[],document-ayoub-hadi-data-engineer-talend-power...,,,,,—,
2,[charaf.kermiche@gmail.com],[06 50 88 09 20],[],[],[],document-charaf-kermiche-developpeur-etl-esb-8...,,,,—,—,—
3,[emhemdihosni@gmail.com],[07 81 63 26 53],[],[],[],document-hosni-mhemdi-lead-full-stack-javascri...,,,,,,—
4,[jbhoussem@gmail.com],[+33 7 82 12 21 17],[],[],[],document-houssemeddine-jebri-senior-developpeu...,,,,,,
5,[lounici.mohand@outlook.fr],[07 58 39 38 26],[linkedin.com/in/mohand-lounici],[],[https://www.fyi-consulting.fr/],document-mohand-lounici-developpeur-business-i...,,,,,,—
6,[oumaimakaddaf19@gmail.com],[06.27.11.29.60],[],[],[],document-oumaima-kaddaf-consultant-talend-2c92...,,,,,,—
7,[laanaya.rashid@gmail.com],[+33 6 17 12 43 20],[],[],[],document-rachid-laanaya-developpeur-javascript...,,,,,—,—
8,[sarrabenosman88@gmail.com],[],[linkedin.com/in/sarra-ben-osman],[],[https://www.linkedin.com/in/sarra-ben-osman/],document-sarra-benosman-data-analyst-3434fad6.pdf,—,,,—,—,—
9,[sin.sim@outlook.fr],[0769555407],"[linkedin.com/in/kikoane, linkedin.com/in/sina...",[github.com/ssi-moha],"[https://github.com/ssi-moha, https://www.link...",document-sinane-si-mohammed-developpeur-react-...,,,,,,—

---
##  Cellule 11 — Récap de l'arborescence des outputs

In [11]:
print(f"\n Structure de {DOSSIER_OUT}/")
for f in sorted(DOSSIER_OUT.rglob("*")):
    niveau = len(f.relative_to(DOSSIER_OUT).parts) - 1
    indent = "   " * niveau + "└─ "
    print(f"{indent}{f.name}")

 Structure de cv_output/
└─ cvs_extraits.csv
└─ cvs_extraits.xlsx
└─ html
   └─ document-achref-amari-data-engineer-talend-9-ans-dexperience-7b0cba2e.html
   └─ document-ayoub-hadi-data-engineer-talend-power-bi-f48843cc.html
   └─ document-charaf-kermiche-developpeur-etl-esb-88ef685f.html
   └─ document-hosni-mhemdi-lead-full-stack-javascript-react-angular-nodejs-9-ans-devops-ci-cd-125a16d7.html
   └─ document-houssemeddine-jebri-senior-developpeur-talend-expert-data-2dfae6a7.html
   └─ document-mohand-lounici-developpeur-business-intelligence-talend-fdd9cc44.html
   └─ document-oumaima-kaddaf-consultant-talend-2c92fb94.html
   └─ document-rachid-laanaya-developpeur-javascript-typescript-react-next-js-angular-node-ef29bc8e (1).html
   └─ document-sarra-benosman-data-analyst-3434fad6.html
   └─ document-sinane-si-mohammed-developpeur-react-js-node-js-dbff0f99 (2).html
└─ json
   └─ document-achref-amari-data-engineer-talend-9-ans-dexperience-7b0cba2e.json
   └─ document-ayoub-hadi-data-engineer-talend-power-bi-f48843cc.json
   └─ document-charaf-kermiche-developpeur-etl-esb-88ef685f.json
   └─ document-hosni-mhemdi-lead-full-stack-javascript-react-angular-nodejs-9-ans-devops-ci-cd-125a16d7.json
   └─ document-houssemeddine-jebri-senior-developpeur-talend-expert-data-2dfae6a7.json
   └─ document-mohand-lounici-developpeur-business-intelligence-talend-fdd9cc44.json
   └─ document-oumaima-kaddaf-consultant-talend-2c92fb94.json
   └─ document-rachid-laanaya-developpeur-javascript-typescript-react-next-js-angular-node-ef29bc8e (1).json
   └─ document-sarra-benosman-data-analyst-3434fad6.json
   └─ document-sinane-si-mohammed-developpeur-react-js-node-js-dbff0f99 (2).json
└─ markdown
   └─ document-achref-amari-data-engineer-talend-9-ans-dexperience-7b0cba2e.md
   └─ document-ayoub-hadi-data-engineer-talend-power-bi-f48843cc.md
   └─ document-charaf-kermiche-developpeur-etl-esb-88ef685f.md
   └─ document-hosni-mhemdi-lead-full-stack-javascript-react-angular-nodejs-9-ans-devops-ci-cd-125a16d7.md
   └─ document-houssemeddine-jebri-senior-developpeur-talend-expert-data-2dfae6a7.md
   └─ document-mohand-lounici-developpeur-business-intelligence-talend-fdd9cc44.md
   └─ document-oumaima-kaddaf-consultant-talend-2c92fb94.md
   └─ document-rachid-laanaya-developpeur-javascript-typescript-react-next-js-angular-node-ef29bc8e (1).md
   └─ document-sarra-benosman-data-analyst-3434fad6.md
   └─ document-sinane-si-mohammed-developpeur-react-js-node-js-dbff0f99 (2).md
└─ txt
   └─ document-achref-amari-data-engineer-talend-9-ans-dexperience-7b0cba2e.txt
   └─ document-ayoub-hadi-data-engineer-talend-power-bi-f48843cc.txt
   └─ document-charaf-kermiche-developpeur-etl-esb-88ef685f.txt
   └─ document-hosni-mhemdi-lead-full-stack-javascript-react-angular-nodejs-9-ans-devops-ci-cd-125a16d7.txt
   └─ document-houssemeddine-jebri-senior-developpeur-talend-expert-data-2dfae6a7.txt
   └─ document-mohand-lounici-developpeur-business-intelligence-talend-fdd9cc44.txt
   └─ document-oumaima-kaddaf-consultant-talend-2c92fb94.txt
   └─ document-rachid-laanaya-developpeur-javascript-typescript-react-next-js-angular-node-ef29bc8e (1).txt
   └─ document-sarra-benosman-data-analyst-3434fad6.txt
   └─ document-sinane-si-mohammed-developpeur-react-js-node-js-dbff0f99 (2).txt